SAPI-254: try to make at least restoring the real sapi service more reliable on test failure

diff --git a/test/runtests b/test/runtests
--- a/test/runtests
+++ b/test/runtests
@@ -67,9 +67,19 @@ function usage
     echo "  -f FILTER   Filter pattern (substring match) for test files to run."
 }
 
+function cleanup () {
+    local status=$?
+    svcadm enable -s sapi
+    if [[ $status -ne 0 ]]; then
+        echo "error $status (run 'TRACE=1 $0' for more info)"
+    fi
+}
+
 
 
 #---- mainline
+
+trap 'cleanup' EXIT
 
 start_time=$(date +%s)
 
@@ -110,8 +120,6 @@ TEST_SAPI_PROTO_MODE=true ./node_modules/.bin/nodeunit \
 TEST_SAPI_PROTO_MODE=false ./node_modules/.bin/nodeunit \
     ./test/${opt_test_pattern}.test.js --reporter tap \
     | tee ${OUTPUT_DIR}/full.tap
-
-svcadm enable -s sapi
 
 
 #---- summary
